// ADMIN_EMAILS removido - agora usamos campo 'role' no Firestore
// Para tornar alguém admin, atualize o documento do usuário: { role: 'admin' }

export const COUNTRIES = [
  { code: 'BR', name: 'Brasil', ddi: '+55', flag: '🇧🇷' },
  { code: 'US', name: 'United States', ddi: '+1', flag: '🇺🇸' },
  { code: 'ES', name: 'España', ddi: '+34', flag: '🇪🇸' },
  { code: 'PT', name: 'Portugal', ddi: '+351', flag: '🇵🇹' },
  { code: 'GB', name: 'United Kingdom', ddi: '+44', flag: '🇬🇧' },
  { code: 'FR', name: 'France', ddi: '+33', flag: '🇫🇷' },
  { code: 'DE', name: 'Deutschland', ddi: '+49', flag: '🇩🇪' },
  { code: 'IT', name: 'Italia', ddi: '+39', flag: '🇮🇹' },
  { code: 'AR', name: 'Argentina', ddi: '+54', flag: '🇦🇷' },
  { code: 'MX', name: 'México', ddi: '+52', flag: '🇲🇽' },
  { code: 'AO', name: 'Angola', ddi: '+244', flag: '🇦🇴' },
  { code: 'MZ', name: 'Moçambique', ddi: '+258', flag: '🇲🇿' },
  { code: 'CV', name: 'Cabo Verde', ddi: '+238', flag: '🇨🇻' },
  { code: 'JP', name: 'Japan', ddi: '+81', flag: '🇯🇵' },
  { code: 'CN', name: 'China', ddi: '+86', flag: '🇨🇳' },
  { code: 'KR', name: 'South Korea', ddi: '+82', flag: '🇰🇷' },
  { code: 'IL', name: 'Israel', ddi: '+972', flag: '🇮🇱' }
];

export const UI_TRANSLATIONS = {
  pt: {
    loginTitle: 'De volta ao princípio',
    loginSubtitle: 'Entre para continuar',
    registerTitle: 'Crie sua conta',
    email: 'Email',
    password: 'Senha',
    name: 'Nome',
    age: 'Idade',
    phone: 'Telefone',
    nationality: 'Nacionalidade',
    selectCountry: 'Selecione o país',
    confirmPassword: 'Confirmar Senha',
    loginBtn: 'Entrar',
    registerBtn: 'Cadastrar',
    googleBtn: 'Entrar com Google',
    guestBtn: 'Entrar como Visitante',
    forgotPass: 'Esqueceu a senha?',
    noAccount: 'Ainda não tem conta? Cadastre-se',
    hasAccount: 'Já tem conta? Fazer Login',
    reading: 'Leitura',
    visuals: 'Visual',
    maps: 'Mapas',
    study: 'Estudo',
    interlinear: 'Interlinear',
    theology: 'Teologia',
    exegesis: 'Exegese',
    library: 'Biblioteca',
    devotionals: 'Devocional',
    more: 'Mais',
    searchPlaceholder: 'Pesquisar na Bíblia...',
    loading: 'Carregando...',
    selectBook: 'Selecionar Livro',
    oldTestament: 'Velho Testamento',
    newTestament: 'Novo Testamento',
    chapter: 'Capítulo',
    compare: 'Comparar',
    profile: 'Meu Perfil',
    save: 'Salvar',
    notes: 'Notas',
    listen: 'Ouvir',
    stop: 'Parar',
    analyze: 'Analisar',
    connectKey: 'Conectar Google Cloud',
    selectKey: 'Selecionar API Key',
    devotionalPrompt: 'Sobre o que você quer refletir hoje?',
    generateDevotional: 'Gerar Devocional',
    share: 'Compartilhar',
    copied: 'Copiado!',
    restorePoints: 'Pontos de Restauração',
    saveRestore: 'Salvar Estado Atual',
    restoreNow: 'Restaurar',
    noRestore: 'Nenhum ponto salvo.',
    dailyDevotional: 'Devocional Diário',
    devotionalTopic: 'Tópico do Devocional',
    devotionalPlaceholder: 'Ex: Fé, Amor, Sabedoria...'
  },
  en: {
    loginTitle: 'Back to the beginning',
    loginSubtitle: 'Sign in to continue',
    registerTitle: 'Create your account',
    email: 'Email',
    password: 'Password',
    name: 'Name',
    age: 'Age',
    phone: 'Phone',
    nationality: 'Nationality',
    selectCountry: 'Select country',
    confirmPassword: 'Confirm Password',
    loginBtn: 'Sign In',
    registerBtn: 'Register',
    googleBtn: 'Sign in with Google',
    guestBtn: 'Continue as Guest',
    forgotPass: 'Forgot password?',
    noAccount: "Don't have an account? Sign up",
    hasAccount: 'Already have an account? Sign in',
    reading: 'Reading',
    visuals: 'Visuals',
    maps: 'Maps',
    study: 'Study',
    interlinear: 'Interlinear',
    theology: 'Theology',
    exegesis: 'Exegesis',
    library: 'Library',
    devotionals: 'Devocional',
    more: 'More',
    searchPlaceholder: 'Search Bible...',
    loading: 'Loading...',
    selectBook: 'Select Book',
    oldTestament: 'Old Testament',
    newTestament: 'New Testament',
    chapter: 'Chapter',
    compare: 'Compare',
    profile: 'My Profile',
    save: 'Save',
    notes: 'Notes',
    listen: 'Listen',
    stop: 'Stop',
    analyze: 'Analyze',
    connectKey: 'Connect Google Cloud',
    selectKey: 'Select API Key',
    devotionalPrompt: 'What do you want to reflect on today?',
    generateDevotional: 'Generate Devotional',
    share: 'Share',
    copied: 'Copied!',
    restorePoints: 'Restore Points',
    saveRestore: 'Save Current State',
    restoreNow: 'Restore',
    noRestore: 'No points saved.',
    dailyDevotional: 'Daily Devotional',
    devotionalTopic: 'Devotional Topic',
    devotionalPlaceholder: 'E.g.: Faith, Love, Wisdom...'
  },
  es: {
    loginTitle: 'De vuelta al principio',
    loginSubtitle: 'Inicia sesión para continuar',
    registerTitle: 'Crea tu cuenta',
    email: 'Correo',
    password: 'Contraseña',
    name: 'Nombre',
    age: 'Edad',
    phone: 'Teléfono',
    nationality: 'Nacionalidad',
    selectCountry: 'Seleccionar país',
    confirmPassword: 'Confirmar Contraseña',
    loginBtn: 'Entrar',
    registerBtn: 'Registrarse',
    googleBtn: 'Entrar con Google',
    guestBtn: 'Entrar como Visitante',
    forgotPass: '¿Olvidaste tu contraseña?',
    noAccount: '¿No tienes cuenta? Regístrate',
    hasAccount: '¿Ya tienes cuenta? Inicia sesión',
    reading: 'Lectura',
    visuals: 'Visuales',
    maps: 'Mapas',
    study: 'Estudio',
    interlinear: 'Interlineal',
    theology: 'Teología',
    exegesis: 'Exégesis',
    library: 'Biblioteca',
    devotionals: 'Devocional',
    more: 'Más',
    searchPlaceholder: 'Buscar en la Biblia...',
    loading: 'Cargando...',
    selectBook: 'Seleccionar Libro',
    oldTestament: 'Antiguo Testamento',
    newTestament: 'Novo Testamento',
    chapter: 'Capítulo',
    compare: 'Comparar',
    profile: 'Mi Perfil',
    save: 'Guardar',
    notes: 'Notas',
    listen: 'Escuchar',
    stop: 'Parar',
    analyze: 'Analizar',
    connectKey: 'Conectar Google Cloud',
    selectKey: 'Seleccionar API Key',
    devotionalPrompt: '¿Sobre qué quieres reflexionar hoy?',
    generateDevotional: 'Generar Devocional',
    share: 'Compartir',
    copied: '¡Copiado!',
    restorePoints: 'Puntos de Restauración',
    saveRestore: 'Guardar Estado Actual',
    restoreNow: 'Restaurar',
    noRestore: 'No hay puntos guardados.',
    dailyDevotional: 'Devocional Diario',
    devotionalTopic: 'Tema del Devocional',
    devotionalPlaceholder: 'Ej: Fe, Amor, Sabiduría...'
  }
};

export const BIBLE_BOOKS = [
  { name: 'Gênesis', nameEn: 'Genesis', nameEs: 'Génesis', chapters: 50, testament: 'VT' },
  { name: 'Êxodo', nameEn: 'Exodus', nameEs: 'Éxodo', chapters: 40, testament: 'VT' },
  { name: 'Levítico', nameEn: 'Leviticus', nameEs: 'Levítico', chapters: 27, testament: 'VT' },
  { name: 'Números', nameEn: 'Numbers', nameEs: 'Números', chapters: 36, testament: 'VT' },
  {
    name: 'Deuteronômio',
    nameEn: 'Deuteronomy',
    nameEs: 'Deuteronomio',
    chapters: 34,
    testament: 'VT'
  },
  { name: 'Josué', nameEn: 'Joshua', nameEs: 'Josué', chapters: 24, testament: 'VT' },
  { name: 'Juízes', nameEn: 'Judges', nameEs: 'Jueces', chapters: 21, testament: 'VT' },
  { name: 'Rute', nameEn: 'Ruth', nameEs: 'Rut', chapters: 4, testament: 'VT' },
  { name: '1 Samuel', nameEn: '1 Samuel', nameEs: '1 Samuel', chapters: 31, testament: 'VT' },
  { name: '2 Samuel', nameEn: '2 Samuel', nameEs: '2 Samuel', chapters: 24, testament: 'VT' },
  { name: '1 Reis', nameEn: '1 Kings', nameEs: '1 Reyes', chapters: 22, testament: 'VT' },
  { name: '2 Reis', nameEn: '2 Kings', nameEs: '2 Reyes', chapters: 25, testament: 'VT' },
  {
    name: '1 Crônicas',
    nameEn: '1 Chronicles',
    nameEs: '1 Crónicas',
    chapters: 29,
    testament: 'VT'
  },
  {
    name: '2 Crônicas',
    nameEn: '2 Chronicles',
    nameEs: '2 Crónicas',
    chapters: 36,
    testament: 'VT'
  },
  { name: 'Esdras', nameEn: 'Ezra', nameEs: 'Esdras', chapters: 10, testament: 'VT' },
  { name: 'Neemias', nameEn: 'Nehemiah', nameEs: 'Nehemías', chapters: 13, testament: 'VT' },
  { name: 'Ester', nameEn: 'Esther', nameEs: 'Ester', chapters: 10, testament: 'VT' },
  { name: 'Jó', nameEn: 'Job', nameEs: 'Job', chapters: 42, testament: 'VT' },
  { name: 'Salmos', nameEn: 'Psalms', nameEs: 'Salmos', chapters: 150, testament: 'VT' },
  { name: 'Provérbios', nameEn: 'Proverbs', nameEs: 'Proverbios', chapters: 31, testament: 'VT' },
  {
    name: 'Eclesiastes',
    nameEn: 'Ecclesiastes',
    nameEs: 'Eclesiastés',
    chapters: 12,
    testament: 'VT'
  },
  { name: 'Cânticos', nameEn: 'Song of Solomon', nameEs: 'Cantares', chapters: 8, testament: 'VT' },
  { name: 'Isaías', nameEn: 'Isaiah', nameEs: 'Isaías', chapters: 66, testament: 'VT' },
  { name: 'Jeremias', nameEn: 'Jeremiah', nameEs: 'Jeremías', chapters: 52, testament: 'VT' },
  {
    name: 'Lamentações',
    nameEn: 'Lamentations',
    nameEs: 'Lamentaciones',
    chapters: 5,
    testament: 'VT'
  },
  { name: 'Ezequiel', nameEn: 'Ezekiel', nameEs: 'Ezequiel', chapters: 48, testament: 'VT' },
  { name: 'Daniel', nameEn: 'Daniel', nameEs: 'Daniel', chapters: 12, testament: 'VT' },
  { name: 'Oseias', nameEn: 'Hosea', nameEs: 'Oseas', chapters: 14, testament: 'VT' },
  { name: 'Joel', nameEn: 'Joel', nameEs: 'Joel', chapters: 3, testament: 'VT' },
  { name: 'Amós', nameEn: 'Amos', nameEs: 'Amós', chapters: 9, testament: 'VT' },
  { name: 'Obadias', nameEn: 'Obadiah', nameEs: 'Abdías', chapters: 1, testament: 'VT' },
  { name: 'Jonas', nameEn: 'Jonah', nameEs: 'Jonás', chapters: 4, testament: 'VT' },
  { name: 'Miqueias', nameEn: 'Micah', nameEs: 'Miqueas', chapters: 7, testament: 'VT' },
  { name: 'Naum', nameEn: 'Nahum', nameEs: 'Nahúm', chapters: 3, testament: 'VT' },
  { name: 'Habacuque', nameEn: 'Habakkuk', nameEs: 'Habacuc', chapters: 3, testament: 'VT' },
  { name: 'Sofonias', nameEn: 'Zephaniah', nameEs: 'Sofonías', chapters: 3, testament: 'VT' },
  { name: 'Ageu', nameEn: 'Haggai', nameEs: 'Hageo', chapters: 2, testament: 'VT' },
  { name: 'Zacarias', nameEn: 'Zechariah', nameEs: 'Zacarías', chapters: 14, testament: 'VT' },
  { name: 'Malaquias', nameEn: 'Malachi', nameEs: 'Malaquías', chapters: 4, testament: 'VT' },
  { name: 'Mateus', nameEn: 'Matthew', nameEs: 'Mateo', chapters: 28, testament: 'NT' },
  { name: 'Marcos', nameEn: 'Mark', nameEs: 'Marcos', chapters: 16, testament: 'NT' },
  { name: 'Lucas', nameEn: 'Luke', nameEs: 'Lucas', chapters: 24, testament: 'NT' },
  { name: 'João', nameEn: 'John', nameEs: 'Juan', chapters: 21, testament: 'NT' },
  { name: 'Atos', nameEn: 'Acts', nameEs: 'Hechos', chapters: 28, testament: 'NT' },
  { name: 'Romanos', nameEn: 'Romans', nameEs: 'Romanos', chapters: 16, testament: 'NT' },
  {
    name: '1 Coríntios',
    nameEn: '1 Corinthians',
    nameEs: '1 Corintios',
    chapters: 16,
    testament: 'NT'
  },
  {
    name: '2 Coríntios',
    nameEn: '2 Corinthians',
    nameEs: '2 Corintios',
    chapters: 13,
    testament: 'NT'
  },
  { name: 'Gálatas', nameEn: 'Galatians', nameEs: 'Gálatas', chapters: 6, testament: 'NT' },
  { name: 'Efésios', nameEn: 'Ephesians', nameEs: 'Efesios', chapters: 6, testament: 'NT' },
  { name: 'Filipenses', nameEn: 'Philippians', nameEs: 'Filipenses', chapters: 4, testament: 'NT' },
  { name: 'Colossenses', nameEn: 'Colossians', nameEs: 'Colosenses', chapters: 4, testament: 'NT' },
  {
    name: '1 Tessalonicenses',
    nameEn: '1 Thessalonians',
    nameEs: '1 Tesalonicenses',
    chapters: 5,
    testament: 'NT'
  },
  {
    name: '2 Tessalonicenses',
    nameEn: '2 Thessalonians',
    nameEs: '2 Tesalonicenses',
    chapters: 3,
    testament: 'NT'
  },
  { name: '1 Timóteo', nameEn: '1 Timothy', nameEs: '1 Timoteo', chapters: 6, testament: 'NT' },
  { name: '2 Timóteo', nameEn: '2 Timothy', nameEs: '2 Timoteo', chapters: 4, testament: 'NT' },
  { name: 'Tito', nameEn: 'Titus', nameEs: 'Tito', chapters: 3, testament: 'NT' },
  { name: 'Filemom', nameEn: 'Philemon', nameEs: 'Filemón', chapters: 1, testament: 'NT' },
  { name: 'Hebreus', nameEn: 'Hebrews', nameEs: 'Hebreos', chapters: 13, testament: 'NT' },
  { name: 'Tiago', nameEn: 'James', nameEs: 'Santiago', chapters: 5, testament: 'NT' },
  { name: '1 Pedro', nameEn: '1 Peter', nameEs: '1 Pedro', chapters: 5, testament: 'NT' },
  { name: '2 Pedro', nameEn: '2 Peter', nameEs: '2 Pedro', chapters: 3, testament: 'NT' },
  { name: '1 João', nameEn: '1 John', nameEs: '1 Juan', chapters: 5, testament: 'NT' },
  { name: '2 João', nameEn: '2 John', nameEs: '2 Juan', chapters: 1, testament: 'NT' },
  { name: '3 João', nameEn: '3 John', nameEs: '3 Juan', chapters: 1, testament: 'NT' },
  { name: 'Judas', nameEn: 'Jude', nameEs: 'Judas', chapters: 1, testament: 'NT' },
  { name: 'Apocalipse', nameEn: 'Revelation', nameEs: 'Apocalipsis', chapters: 22, testament: 'NT' }
];

export const AVAILABLE_TRANSLATIONS = [
  { id: 'NVI', label: 'Nova Versão Internacional', lang: 'pt' },
  { id: 'ACF', label: 'Almeida Corrigida Fiel', lang: 'pt' },
  { id: 'ARA', label: 'Almeida Revista e Atualizada', lang: 'pt' },
  { id: 'NAA', label: 'Nova Almeida Atualizada', lang: 'pt' },
  { id: 'KJ1611', label: 'King James 1611 (Fiel)', lang: 'pt' },
  { id: 'NTLH', label: 'Nova Tradução na Linguagem de Hoje', lang: 'pt' },
  { id: 'NVT', label: 'Nova Versão Transformadora', lang: 'pt' },
  { id: 'KJA', label: 'King James Atualizada', lang: 'pt' },
  { id: 'Bíblia Infantil', label: 'Bíblia Infantil (Kids)', lang: 'pt' },
  { id: 'Bíblia Teen', label: 'Bíblia Teen (Adolescentes)', lang: 'pt' },
  { id: 'Almeida com Strong', label: 'Almeida com Strong', lang: 'pt' },
  // English
  { id: 'NIV', label: 'New International Version', lang: 'en' },
  { id: 'KJV', label: 'King James Version', lang: 'en' },
  { id: 'ESV', label: 'English Standard Version', lang: 'en' },
  { id: 'Kids Bible', label: "Children's Bible", lang: 'en' },
  // Spanish
  { id: 'RVR1960', label: 'Reina Valera 1960', lang: 'es' },
  { id: 'NVI-ES', label: 'Nueva Versión Internacional', lang: 'es' },
  { id: 'Biblia Niños', label: 'Biblia para Niños', lang: 'es' }
];

export const ABBREVIATION_MAP: Record<string, string> = {
  Gn: 'Gênesis',
  Ex: 'Êxodo',
  Lv: 'Levítico',
  Nm: 'Números',
  Dt: 'Deuteronômio',
  Js: 'Josué',
  Jz: 'Juízes',
  Rt: 'Rute',
  '1Sm': '1 Samuel',
  '2Sm': '2 Samuel',
  '1Rs': '1 Reis',
  '2Rs': '2 Reis',
  '1Cr': '1 Crônicas',
  '2Cr': '2 Crônicas',
  Ed: 'Esdras',
  Ne: 'Neemias',
  Et: 'Ester',
  Jó: 'Jó',
  Sl: 'Salmos',
  Pv: 'Provérbios',
  Ec: 'Eclesiastes',
  Ct: 'Cânticos',
  Is: 'Isaías',
  Jr: 'Jeremias',
  Lm: 'Lamentações',
  Ez: 'Ezequiel',
  Dn: 'Daniel',
  Os: 'Oseias',
  Jl: 'Joel',
  Am: 'Amós',
  Ob: 'Obadias',
  Jn: 'Jonas',
  Mq: 'Miqueias',
  Na: 'Naum',
  Hc: 'Habacuque',
  Sf: 'Sofonias',
  Ag: 'Ageu',
  Zc: 'Zacarias',
  Ml: 'Malaquias',
  Mt: 'Mateus',
  Mc: 'Marcos',
  Lc: 'Lucas',
  Jo: 'João',
  At: 'Atos',
  Rm: 'Romanos',
  '1Co': '1 Coríntios',
  '2Co': '2 Coríntios',
  Gl: 'Gálatas',
  Ef: 'Efésios',
  Fp: 'Filipenses',
  Cl: 'Colossenses',
  '1Ts': '1 Tessalonicenses',
  '2Ts': '2 Tessalonicenses',
  '1Tm': '1 Timóteo',
  '2Tm': '2 Timóteo',
  Tt: 'Tito',
  Fm: 'Filemom',
  Hb: 'Hebreus',
  Tg: 'Tiago',
  '1Pe': '1 Pedro',
  '2Pe': '2 Pedro',
  '1Jo': '1 João',
  '2Jo': '2 João',
  '3Jo': '3 João',
  Jd: 'Judas',
  Ap: 'Apocalipse'
};
